// jsonData.jg

let json = `[{"id":1,"first_name":"Agnella","last_name":"Bertelsen","email":"abertelsen0@phoca.cz","gender":"Female","salary":6816},
{"id":2,"first_name":"Beverie","last_name":"O'Neill","email":"boneill1@google.es","gender":"Female","salary":2829},
{"id":3,"first_name":"Cristian","last_name":"Minero","email":"cminero2@xrea.com","gender":"Male","salary":3197},
{"id":4,"first_name":"Benjy","last_name":"Tesseyman","email":"btesseyman3@unc.edu","gender":"Male","salary":8658},
{"id":5,"first_name":"Marina","last_name":"Gillinghams","email":"mgillinghams4@creativecommons.org","gender":"Female","salary":8476},
{"id":6,"first_name":"Eb","last_name":"Reaveley","email":"ereaveley5@spiegel.de","gender":"Male","salary":7189},
{"id":7,"first_name":"Chaim","last_name":"Allchorn","email":"callchorn6@cnet.com","gender":"Male","salary":2700},
{"id":8,"first_name":"Sara-ann","last_name":"Segge","email":"ssegge7@msn.com","gender":"Female","salary":7450},
{"id":9,"first_name":"Mufi","last_name":"Lars","email":"mlars8@twitter.com","gender":"Female","salary":5986},
{"id":10,"first_name":"Steffie","last_name":"Reddyhoff","email":"sreddyhoff9@timesonline.co.uk","gender":"Female","salary":2579},
{"id":11,"first_name":"Terza","last_name":"Watts","email":"twattsa@arstechnica.com","gender":"Female","salary":2917},
{"id":12,"first_name":"Bertie","last_name":"Rime","email":"brimeb@hostgator.com","gender":"Non-binary","salary":4840},
{"id":13,"first_name":"Randi","last_name":"Dailey","email":"rdaileyc@wikimedia.org","gender":"Female","salary":8811},
{"id":14,"first_name":"Antin","last_name":"Wooffinden","email":"awooffindend@cisco.com","gender":"Male","salary":6170},
{"id":15,"first_name":"Benjie","last_name":"Eadie","email":"beadiee@ning.com","gender":"Male","salary":7642},
{"id":16,"first_name":"Kendrick","last_name":"Giraudeau","email":"kgiraudeauf@storify.com","gender":"Male","salary":3998},
{"id":17,"first_name":"Britt","last_name":"Petlyura","email":"bpetlyurag@timesonline.co.uk","gender":"Male","salary":4683},
{"id":18,"first_name":"Dagny","last_name":"Copeman","email":"dcopemanh@mac.com","gender":"Male","salary":6685},
{"id":19,"first_name":"Leland","last_name":"Fraine","email":"lfrainei@fastcompany.com","gender":"Female","salary":4353},
{"id":20,"first_name":"Isabel","last_name":"McGee","email":"imcgeej@baidu.com","gender":"Female","salary":8178}]`;